### ISSUE TITLE
Proposal: Merge backend implementations (ring and hash) for improved user experience

### ISSUE THREAD

**Issue by edwinjhlee** [Metaphorme/ezcheck#1]
作者你好，
    
您是否考虑过将两种后端实现（环形和哈希）合并成一个呢？合并后的实现可以在目标平台支持 “ring” 后端时使用它，否则就回退到 “hash" 后端。
    
目前，编译后的二进制文件大小相当小。即使合并这两个后端会使其大小翻倍（达到大约 1MB），我认为它仍然在一个合理的范围内。
    
这种整合可以通过简化构建过程并确保跨平台的一致行为来改善用户体验。

---

Hi Author,
    
Could you consider merging the two backend implementations (ring and hash) into a single one?  The merged implementation could use the `ring` backend when it's available on the target platform, and fall back to the `hash` backend otherwise.
    
Currently, the compiled binary size is quite small.  Even if merging these backends doubles the size (to ~1MB), I believe it would still be reasonably small.
    
This consolidation would improve the user experience by simplifying the build process and ensuring consistent behavior across platforms.

**Comment by Metaphorme** [comment]
谢谢你，这是一个非常好的议题，也是我一直在思考的问题。要回答这个问题，首先要回答这些问题。回答部分是我个人的答案，并不一定准确，更多的是抛砖引玉，分享个人的见解。

1. 用户常用的Hash算法有哪些？

    目前我遇到的与校验文件完整性相关的Hash算法主要有：MD5, SHA256, SHA512。但 2024 年究竟还有多少人在用 MD5？

2. MD5 真的不安全吗？

    以下内容参考了这篇[帖子](https://security.stackexchange.com/questions/186657/is-it-secure-to-use-md5-to-verify-the-integrity-of-small-files-less-than-15kb)。
    
    这取决于使用者的目的（错误来源的信心）。
    
    * 对于随机、意外的错误，MD5 可以有效的检测，出现 Hash 冲突的概率非常小，是可靠的；
    
    * 对于攻击者有意创建、影响的文件，是不可靠的。

3. ezcheck 这个工具创建的目的是什么？

    ezcheck 创建的本意是提供一个在各个平台都有相同的检测、校验逻辑的工具。统一 Windows 的 certutil、各种 GNU 工具（shasum、md5），并提供统一的输出格式。
    
    > 现代的加密工具不应包含已知不安全的加密算法或存在已知弱点的算法。
    
    ezcheck 并不鼓励用户使用 MD5 等已经证明不安全的算法，但是就使用便捷性、兼容性而言，提供 MD5 是一个有趣的权衡。

4. ring 后端的平台兼容性究竟如何？使用 ring 作为默认后端的可能性？

    ring 兼容性列表可以从[这里](https://github.com/briansmith/ring/blob/main/mk/cargo.sh#L66)看到，实际上已经包含了大部分主流平台。但为什么我仍然对 ring 后端的兼容性存疑？主要原因是 boringssl（ring 的实际后端）直到2024年8月才将 aarch64-apple-darwin 提升到 Tier 1，这让我感受很深刻。诚然，写出高效、优质的汇编实现高性能的加密算法是非常困难的，非常感谢他们的工作，但是不能忽视 boringssl 这类工具支持新平台的延迟性。

    对于将 ring 作为默认后端来说，最大的困难之处在于其不能提供 MD5 这个常用但不安全的算法，但是用户是否真的需要 MD5吗？使用 ring 后端的优势之一在于其阻止了用户继续使用 MD5 这个不安全的算法，但损失了兼容性，另外，其最大优势是与 GNU 工具相媲美的性能。


5. 关于混合后端的可能性？

    > 默认即最优。

    是否可以提供混合后端，将 MD2、MD4、MD5、SHA1、SHA224 这类 ring 不支持的算法使用 hashes 实现，其他算法由 ring 实现？显而易见的好处包括：
    
    * 总是有最佳的性能
    * 最广的算法兼容性
    
    不足包括：
    
    * 是否有鼓励用户继续使用不安全算法的嫌疑
    * 对新平台的兼容性较差
    
以上是我的个人观点，还请多指正、多讨论。

**Comment by edwinjhlee** [comment]
是否有鼓励用户继续使用不安全算法的嫌疑

---
我觉得这点自由抉择可以交给用户，使用的场景很多，例如只是需要一定规模模数据的的查重，这就不需要算力要求高的算法。

至于要引导用户，加一个 log 就可以解决。

**Comment by edwinjhlee** [comment]
对新平台的兼容性较差
---

不会啦，新平台如果没有 ring 优化的，就用 hashes 后端。条件编译就好了。

**Comment by Metaphorme** [comment]
发布新版本：https://github.com/Metaphorme/ezcheck/releases/tag/0.1.3
